---
# tasks file for ucsdlib.imagemagick-JPEG2000

- name: Get per OS Family Package Name
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install ImageMagick
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ imagemagick_jpeg2000_packages }}'
  become: true
